### PR TITLE
Flatpak

### LINKED ISSUE #59: Bundled libraries are not installed.
This is seen on the flatpak build, perhaps also on others.

The library libsgllnx64-2.29.02.so which lives under buildlinux64 is not included in the tarball, and thus missing in runtime. The symptoms are as described in #48. There is also lot's of console output  about the missing, not found library.

Manually adding it resolves the first error and reveals a new: libsgllnx64-2.29.02.so depends on libusb-0.1.so.4  which is not generally available (outdated). We need to provide also this (or rebuild libsgllnx against a newer distro).

libusb does not seem to have any specific runtime deps.

### PR DESCRIPTION
**Pull request by leamas**
One commit on top the ci branch, aimed to fix #59 
Closes: #59

### CODE REVIEW

**Comment by leamas** [comment]
BTW: While you are on it: Could you update the beta branch with the new build when it becomes available?

**Comment by bdbcat** [comment]
Alec...
Pushed to Beta catalog.
Closing this PR manually.  Please base any further updates to oesenc_pi on branch "ci"

**Comment by leamas** [comment]
Thanks for merge & close!

Just FYI:  Both my PRs (also this) have been rebased on the ci branch. Unfortunately, this is how it looks when making a standard github PR. The alternative would be to just attach one or more patch files. Would this be better?

**Comment by bdbcat** [comment]
Alec...
Standard PR is certainly easier for me.  I just need to look more closely at the diffs, to make sure my local work is not overwritten if I have not yet pushed.

**Pull request closed without merging**
