### PR TITLE
Ci 1751: Fix macos installation paths

### PR DESCRIPTION
**Pull request by leamas**
It actually turns out that I seem to have somehow dropped these patches also in my oesenc. 

This seems to clean up the paths here. A view of the package contents is available at  https://cloudsmith.io/~alec-leamas/repos/opencpn-plugins-unstable/packages/detail/raw/oesenc-darwin-10.13.6-tarball/1.2.0.3.1c33e62/#files.

(The history was rewritten before making this PR).

This PR is against the ci branch.

### CODE REVIEW

**Comment by leamas** [comment]
I forgot to mention that is two commits on top of the ci branch.

**Comment by bdbcat** [comment]
Alec...
I did not have the nerve to merge this as-is.  Yikes....
Manually made the updates to my repo.

**Comment by leamas** [comment]
Yes, I figured. Handling PRs to non-master branch is a mess. 

Since master is more or less in a frozen state now: perhaps you should configure the ci branch as the default one? This should make the PRs against ci straight-forward. 

Sorry for not making these tests earlier. My macos VM has been in a sad state. It's now resurrected, so that part is no problem. I'll try to do some more tests later.

**Comment by leamas** [comment]
Fixed. Closing.

**Comment by rgleason** [comment]
What does building buster do?   Commented it out.
Also I think I am going to put mingw back in since OpenCPN still has it. OK?

**Comment by leamas** [comment]
You are free to put whatever you want back, it's your show. I just mention what I think has a lower priority of time or builders are scarce.

Besides the ubuntu/x86_64 for desktops we also build for raspberrry pie. IMHO, the main focus  should be Raspbian/armhf. However, it is also possible to run official Debian on Rpi, buster/armel is the current release.  It's @bdbcat  who have added the RPi builds, talk to him about it.

**Comment by rgleason** [comment]
Thanks, buster can easily be added back later, 2 raspbian/armhf are in and working.  now following the gtk3 commits.

**Pull request closed without merging**
