### PR TITLE
Flatpak: Update runtime to 20.08 

### PR DESCRIPTION
**Pull request by leamas**
See https://github.com/OpenCPN/OpenCPN/issues/2273.

This will create metadata and tarballs with separate names from the 18.08 ones. Both the previous 18.08 and the new 20.08 builds can thus co-exist in the catalog.

EDIT: While on it, add the ip command also here. I have the impression that it simplifies. If not, just revert 31293b9f
EDIT2: CircleCI build logs [here](https://app.circleci.com/pipelines/github/leamas/oesenc_pi/302/workflows/558cbbdb-4887-4326-967d-1aec562572f2)

### CODE REVIEW

**Comment by leamas** [comment]
To test this you must install the flatpak beta version which uses 20.08:

    $ flatpak install --user https://flathub.org/beta-repo/appstream/org.opencpn.OpenCPN.flatpakref

**Comment by leamas** [comment]
The Travis build error is unrelated, it's about docker.io which wants us to authenticate.

**Comment by bdbcat** [comment]
Hmmm...
Looks like we are completely replacing 18.08, in favor of 20.08.  Won't this mean that any currently happy 18.08 users will get no further oeSENC_PI updates unless they upgrade to 20.08?     But there is no OCPN 5.2.4 for 20.08, is there?  So they will have to wait for OCPN 5.6, then. 
Not objecting to this policy, just want to be sure that existing 18.08 users can still play, and are not left out in the cold, so to speak.

**Comment by leamas** [comment]
> Looks like we are completely replacing 18.08, in favor of 20.08. Won't this mean that any currently happy 18.08 users will get no further oeSENC_PI updates

Yes. But my idea for now is to just get a test shot out of the doors. There are no code changes involved, so this version will be the same for 18.08 and 20.08.

After checking if/how it works we need to decide if the 5.6.0 opencpn flatpak will be using 20.08 or 18.08.  Depending on that decision, we then start building plugins either for 18.08, 20.08 or both.  As traditional, we are using oeseend as an example of a worst case plugin -- if it works here, it probably works for the others.

**Comment by bdbcat** [comment]
Merged, in CircleCI queue. Some troubles there, I guess..

**Comment by leamas** [comment]
But you have not published it, right?

Attaching a test build done from current master@e65b064. To test this:

  - Install and run the beta version of OpenCPN using the 20.08 runtime:
 
         $ flatpak install --user https://flathub.org/beta-repo/appstream/org.opencpn.OpenCPN.flatpakref
         $ flatpak run org.opencpn.OpenCPN//beta
 
 - Save and import the attached plugin.

There is no need to uninstall an existing flatpak, it can co-exist with the beta. You might need to use `flatpak run org.opencpn.OpenCPN//stable` to be sure to use the stable version, though.

There might be warnings about incompatible plugins if you have installed plugins using the regular Flatpak version. These warninga are not significant. Likewise, the plugin catalog is empty, this is expected.



[oeSENC-4.2.19.28_flatpak-20.08-x86_64.tar.gz](https://github.com/bdbcat/oesenc_pi/files/6526109/oeSENC-4.2.19.28_flatpak-20.08-x86_64.tar.gz)

**Comment by bdbcat** [comment]
Alec...
Not published.  CircleCI had some outage yesterday, so I restarted the build.  Seems to be finished OK  now.  Time to test it by import.

**Comment by leamas** [comment]
Dave,

Others are looking... Perhaps you could share the cloudsmith download link so testers can use the "official" builds rather than my home.grown?

**Comment by bdbcat** [comment]
o-charts_pi just finished building now, with aarch64 patch.
https://dl.cloudsmith.io/public/david-register/ocpn-plugins-unstable/raw/names/o-charts-0.9-flatpak-aarch64-20.08-tarball/versions/0.9.0.17/o-charts-0.9.0.17_flatpak-20.08-aarch64.tar.gz

I need to add the aarch64 path to oeSENC_PI, and wait for CI build.

**Comment by leamas** [comment]
... and the x86_64 build against 20.08 is here: https://dl.cloudsmith.io/public/david-register/ocpn-plugins-unstable/raw/names/oeSENC-4.2-flatpak-x86_64-20.08-tarball/versions/4.2.19.28/oeSENC-4.2.19.28_flatpak-20.08-x86_64.tar.gz

**Comment by bdbcat** [comment]
... And one more, flatpak-aarch64/20.08
https://dl.cloudsmith.io/public/david-register/ocpn-plugins-unstable/raw/names/oeSENC-4.2-flatpak-aarch64-20.08-tarball/versions/4.2.19.28/oeSENC-4.2.19.28_flatpak-20.08-aarch64.tar.gz

**Pull request merged**
