### PR TITLE
Gtk3

### PR DESCRIPTION
**Pull request by leamas**
It turns out that building against wxgtk3 basically is about using update-alternatives to set wx-config to point the the gtk3 version, simple enough. 

Set PKG_TARGET to the new ubuntu-gtk3 value, and update build scripts.

While on it, mute warnings from cmake and fix a nasty windows bug (last commit). Also, restore the CLOUDSMITH_STABLE_REPO and CLOUDSMITH_UNSTABLE_REPO used elsewhere to
define the cloudsmith deployment repos.

### CODE REVIEW

**Comment by leamas** [comment]
The build error looks OK,  same code passed one of the other travis builders. Probably some arm hardware which refused to handle the load.

**Comment by rgleason** [comment]
I don't really understand the impact of this
> These packages are available in trusty+. The base-files
>  fallback is for optional packages available in later releases.

...and I have no idea what happens with various env here

but won't these removals affect plugins such as weatherfax, rtlsdr, etc
https://github.com/bdbcat/oesenc_pi/pull/70/commits/357da06b9ee89f5a0d4404dfb513450c1d89c3ff
libwxsvg-dev | base-files,
portaudio19-dev,

**Comment by leamas** [comment]
>  I don't really understand the impact of this.

It basically says that this control file is valid from trusty and upwards.  Since there is no way to express that package is optional we are using constructs like l`ibunarr-dev | base-files (<< 11),` which means that either install unarr-dev or, on a debian version <  11 (bullseye) just use base-files. In short: on versions before 11, don't install anything, otherwise install libunarr-dev.

> but won't these removals affect plugins such as...

Doubt that. Just try, you could re-add them if there is a build error.

Overall, the problem with that list is that it is too long. Installing unused packages takes time.

**Comment by rgleason** [comment]
Ok, but I know from building weatherfax as a standalone compile (not in-liine with O) that portaudio is absolutely needed.

**Comment by leamas** [comment]
In which case you add it for weahterfax.  But there is no need for other plugins, which doesn't use, to carry this dependency. 

It is expected that different plugins adds specific dependencies

**Pull request merged**
